DROP TABLE USER_ROLES;
TRUNCATE TABLE S_PASSWORD;
ALTER TABLE S_PASSWORD ADD COLUMN ACTIVE BOOLEAN DEFAULT FALSE;
CREATE FUNCTION PG_TEMP.CREATE_PASSWORD(UNAME VARCHAR)
RETURNS BOOLEAN AS $$
DECLARE PASSED BOOLEAN;
BEGIN		
        INSERT INTO 
		S_PASSWORD(PASSWORD_TEXT, S_USER_ID, CREATED_BY, ACTIVE) 
		VALUES((SELECT PASSWORD FROM USER_LOGINS WHERE USER_NAME=$1), (SELECT ID FROM S_USER WHERE LOGIN =$1), 'SYSTEM', TRUE);

        RETURN PASSED;
END;
$$  LANGUAGE PLPGSQL;
TRUNCATE TABLE S_PASSWORD;
SELECT PG_TEMP.CREATE_PASSWORD(U.USER_NAME), U.USER_NAME
FROM USER_LOGINS U;
DROP TABLE IF EXISTS USER_TOKEN CASCADE;
DROP TABLE IF EXISTS USER_LOGINS CASCADE;
ALTER TABLE s_password DROP CONSTRAINT IF EXISTS idx_s_password;
DROP INDEX IF EXISTS idx_s_password;