/**
 * Шаблоны для экраны отображения cleanse функций
 *
 * @author Sergey Shishigin
 * @date 2018-03-15
 */
Ext.define('Unidata.view.admin.compositeCleanseFunction.editor.CompositeCleanseFunctionTemplate', {
    singleton: true,

    cleanseFunctionTpl: ['<div class="unidata-cfblock-title"><div class="unidata-cfblock-title-icon unidata-cfblock-title-icon-function"></div><div class="unidata-cfblock-title-text">{cleanseFunction.data.name} {nodeId}</div>',
        '    <div class="unidata-cfblock-remove"></div>',
        '</div>',
        '<div class="unidata-cfblock">',
        '<div class="unidata-cfblock-inputs">',
        '    <tpl for="cleanseFunction.nestedData.inputPorts">',
        '        <div class="unidata-cfblock-row">',
        '            <div class="unidata-cfblock-port" title="{description} {dataType}" data-node-id="{parent.nodeId}"',
        '                 data-port-datatype="{dataType}"',
        '                 data-port-required="{required}"',
        '                 data-port-name="{name}" id="un-ccf-{parent.id}-inputport-{name}">',
        '                {description}',
        '                <span>{dataType}</span>',
        '            </div>',
        '        </div>',
        '    </tpl>',
        '</div>',
        '<div class="unidata-cfblock-outputs">',
        '    <tpl for="cleanseFunction.nestedData.outputPorts">',
        '        <div class="unidata-cfblock-row">',
        '            <div class="unidata-cfblock-port"',
        '                 title="{description} {dataType}" data-node-id="{parent.nodeId}" data-port-datatype="{dataType}"',
        '                 data-port-name="{name}"',
        '                 data-port-required="{required}"',
        '                 id="un-ccf-{parent.id}-outputport-{name}">',
        '                {description}',
        '                <span>{dataType}</span></div>',
        '        </div>',
        '    </tpl>',
        '</div>',
        '</div>'],

    inputPortsTpl: ['<div class="unidata-inputports">',
        '    <tpl for="inputPorts">',
        '        <div class="unidata-inputports-row"',
        '             data-port-datatype="{dataType}"',
        '             data-port-required="{required}"',
        '             data-port-name="{name}"',
        '             data-node-id="0" id="un-ccf-inputports-outputport-{name}">',
        '            <div class="unidata-inputports-port">',
        '                <div class="unidata-inputport-item">',
        '                    {description:htmlEncode}',
        '                </div>',
        '                <div class="unidata-inputport-datatype">{dataType}</div>',
        '            </div>',
        '        </div>',
        '    </tpl>',
        '</div>'],

    outputPortsTpl: ['<div class="unidata-outputports">',
        '    <tpl for="outputPorts">',
        '        <div class="unidata-outputports-row"',
        '             data-port-datatype="{dataType}"',
        '             data-port-required="{required}"',
        '             data-port-name="{name}"',
        '             data-node-id="1"',
        '             id="un-ccf-outputports-inputport-{name}">',
        '            <div class="unidata-outputports-port">',
        '                <div class="unidata-outputport-item">',
        '                    {description:htmlEncode}',
        '                </div>',
        '                <div class="unidata-outputport-datatype">{dataType:htmlEncode}</div>',
        '            </div>',
        '        </div>',
        '    </tpl>',
        '</div>'],

    portConstantTpl: ['<div class="unidata-cfblock-title"><div class="unidata-cfblock-title-icon unidata-cfblock-title-icon-constant"></div><div class="unidata-cfblock-title-text">Константа: <span class="unidata-cfblock-title-datatype">{data.type}</span></div>',
        '<div class="unidata-cfblock-remove"></div>',
        '</div>',
        '<div class="unidata-cfblock unidata-cfblock-constant">',
        '<div style="width: 100%" class="unidata-cfblock-outputs">',
        '        <div class="unidata-cfblock-row">',
        '            <div class="unidata-cfblock-port',
        '                 <tpl if="data.displayValue">',
        '            unidata-cfblock-port-constant"',
        '                 <tpl else>',
        '            unidata-cfblock-port-constant-empty-text"',
        '                 </tpl>',
        '                 title="{data.displayValue} ({data.type})" data-port-datatype="{data.type}"',
        '                 data-node-id="{id}"',
        '                 data-port-name="port0"',
        '                 data-port-required="true"',
        '                 id="un-ccf-constant-{id}-outputport-port0">',
        '                 <tpl if="data.displayValue">',
        '                   {data.displayValue}',
        '                 <tpl else>',
        Unidata.i18n.t('admin.cleanseFunction>selectConstantEmptyText'),
        '                 </tpl>',
        '                 </div>',
        '        </div>',
        '</div>',
        '</div>'
    ],

    ifThenElseTpl: [
        '<div class="unidata-cfblock-remove-ifthenelse"></div>',
        '<div class="unidata-cfblock-ifthenelse unidata-cfblock-ifthenelse-{size}" id="{id}"></div>',
        '<div class="unidata-cfblock-ifthenelse-horizontal-line-{size}"></div>',
        '<div class="unidata-cfblock-ifthenelse-vertical-line-{size}"></div>',
        '<tpl if="fullText">',
            '<div class="unidata-cfblock-ifthenelse-true-label-{size}">TRUE</div>',
            '<div class="unidata-cfblock-ifthenelse-false-label-{size}">FALSE</div>',
        '<tpl else>',
            '<div class="unidata-cfblock-ifthenelse-true-label-{size}">T</div>',
            '<div class="unidata-cfblock-ifthenelse-false-label-{size}">F</div>',
        '</tpl>'

    ]
});
